### ISSUE TITLE
Translation disappears when switching from “List mode” to “Source mode”

### ISSUE THREAD

**Issue by GitGianluc** [URUWorks/TeroSubtitler#104]
Steps to reproduce:

1. Launch Tero Subtitler.
2. Click on `New empty subtitle` on startup and load a video.
3. Load the relevant subtitles or go to `Video > Audio to text…` to generate them.
4. Go to `Tools > Auto translate…`, select the `All subtitles` checkbox and click the `Translate` button (no matter what languages are chosen as “Source” and “Translation”).
5. Switch from “List mode” to “Source mode” and back: the translated text will be gone.

https://github.com/URUWorks/TeroSubtitler/assets/16348719/711e3c76-bf67-4414-ac57-6e1c44528f55

**Comment by URUWorks** [comment]
This happens because the format selected before going to source view does not supports (saves) translation, if you try it with the "Tero Subtitler" format it works correctly :)

**Comment by GitGianluc** [comment]
> If you try it with the "Tero Subtitler" format it works correctly :)

Yes, I see. Is the “Tero Subtitler” format the only one which supports translation mode (perhaps because it has an XML structure)?

> What could be done, if they are in translation mode, when switching to source mode, automatically set to the "Tero Subtitler" format and not lose the translation?

It's a good workaround, but I would suggest adding an alert dialogue indicating the automatic format conversion.
