### ISSUE TITLE
Resize handles for columns do not show a preview of the dragging result

### ISSUE THREAD

**Issue by GitGianluc** [URUWorks/TeroSubtitler#105]
Steps to reproduce:

1. Launch Tero Subtitler.
2. Click on `New empty subtitle` on startup.
3. Try dragging the left edge of the video player to resize the column: you will see the resizing handles, but the preview of the resizing outcome (i.e., where and how much the column will be resized) will not be visible.

> **Question**: is this a bug specific to macOS? Further investigations are needed to determine that.

https://github.com/URUWorks/TeroSubtitler/assets/16348719/c62eabcd-842a-4d39-8453-8883d6905f59

Using Tero Subtitler 1.0.0.3 - macOS Ventura 13.4 / MacBook Air M2

**Comment by URUWorks** [comment]
Fixed v1.0.0.4
