### ISSUE TITLE
Video title not displayed

### ISSUE THREAD

**Issue by RoxMarty** [URUWorks/TeroSubtitler#118]
When loading a video, its title is not displayed in the window title bar

**Comment by URUWorks** [comment]
When should it be?
I guess in transcription mode?

**Comment by RoxMarty** [comment]
> When should it be? I guess in transcription mode?

1) Video\Open video\(Filename.mkv)

And I can't see (Filename) at the title bar.

2) Video\Audio to text\Transcribing...

After complete I see the transcribed Text but I don't see its (Filename)

P.S. And see Issue #113, #117 and #119

**Comment by URUWorks** [comment]
I understand, when you don't have any subtitle file loaded, open a video and there is nothing in the title.
