### ISSUE TITLE
Blocked save function

### ISSUE THREAD

**Issue by RoxMarty** [URUWorks/TeroSubtitler#119]
When transcribing is finished, the subtitle and menu window is blocked to be able to save it. The solution I found: temporarily switch from list mode to transcribing mode and back, then saving will be available

**Comment by chenlung** [comment]
Can you please update your issues with the version and OS you're using? Thanks!

**Comment by RoxMarty** [comment]
My OS: Windows 11 (x64) 22H2 22621.963
Tero Subtitler 1.0.0.5

**Comment by URUWorks** [comment]
In transcription mode, to save your transcription text, the "Export/Transcription..." menu is enabled.

**Comment by RoxMarty** [comment]
> In transcription mode, to save your transcription text, the "Export/Transcription..." menu is enabled.

There are no menu items available
![2023-07-02  00-05-(49)](https://github.com/URUWorks/TeroSubtitler/assets/105894506/086c6a6b-5227-42d4-8bf4-f4f7eada2253)

**Comment by URUWorks** [comment]
Oh sorry, I understood that it was Tero's transcription mode, but you mean "Audio-to-text"...
You are right, it is an bug... It will be fixed for the next version.
