### ISSUE TITLE
The names of the menu items are not displayed

### ISSUE THREAD

**Issue by RoxMarty** [URUWorks/TeroSubtitler#121]
The names of the menu items are not displayed:

![изображение](https://github.com/URUWorks/TeroSubtitler/assets/105894506/b1c2704b-7632-482c-9f3a-bb56537907d9)

![изображение](https://github.com/URUWorks/TeroSubtitler/assets/105894506/ed0eff5e-e512-4cee-ac5e-f092fbe5e8ac)

**Comment by chenlung** [comment]
Hi, can you update your post with the build and version, please? Thanks!
