### ISSUE TITLE
Move subtitle to current time

### ISSUE THREAD

**Issue by RoxMarty** [URUWorks/TeroSubtitler#122]
Would you return this hot key from old other versions?
It needs for directly move current subtitle to current time quickly

![изображение](https://github.com/URUWorks/TeroSubtitler/assets/105894506/dbe7b05d-1bf2-4974-9e37-51df2e79afb4)
![изображение](https://github.com/URUWorks/TeroSubtitler/assets/105894506/566132d9-b123-4fd1-a36b-80dca1ce0902)
![изображение](https://github.com/URUWorks/TeroSubtitler/assets/105894506/fd05de39-c5cf-49fb-a61f-8dc79c30ba7d)

**Comment by URUWorks** [comment]
of course, it will be ready for the next version.
