### ISSUE TITLE
Save project

### ISSUE THREAD

**Issue by RoxMarty** [URUWorks/TeroSubtitler#123]
Would you add possibility from old versions: save current project (Original+Translation)?
For example:
![изображение](https://github.com/URUWorks/TeroSubtitler/assets/105894506/1afe5bc5-2ea5-4069-8a39-02d135e10053)
![изображение](https://github.com/URUWorks/TeroSubtitler/assets/105894506/1a2ef396-e6c4-441e-acff-0dbbacd3b356)

**Comment by URUWorks** [comment]
Of course :)
