### ISSUE TITLE
Delay is not set

### ISSUE THREAD

**Issue by RoxMarty** [URUWorks/TeroSubtitler#124]
Delay is not set. No change at all
![изображение](https://github.com/URUWorks/TeroSubtitler/assets/105894506/78eb6386-fa56-44b9-ba4a-23f497784676)

**Comment by URUWorks** [comment]
Can you explain me?
Are the times not modified when applying?

**Comment by chenlung** [comment]
Can you please supply steps, a sample file to reproduce with, the OS, and the version you are using?

**Comment by RoxMarty** [comment]
> Are the times not modified when applying?

Yes. Exactly. No changes with any numbers. Any subtitles. Even the new

**Comment by URUWorks** [comment]
I can't recreate this issue, can you explain the steps to follow?

**Comment by RoxMarty** [comment]
> can you explain the steps to follow?

I recorded video: https://youtu.be/VCx6xbo1gGc

**Comment by URUWorks** [comment]
Thanks.

**Comment by URUWorks** [comment]
@RoxMarty can you contact me at [discord](https://discord.com/invite/EqzXEa8pHK)?

**Comment by URUWorks** [comment]
Fixed v1.0.0.7
