### ISSUE TITLE
Missed unclosed Form Name

### ISSUE THREAD

**Issue by RoxMarty** [URUWorks/TeroSubtitler#131]
Tero 1.0.0.7
Maybe you forgot to close "Form Name" from this string:

`  <Form Name="frmDelay" Caption="Set delay"/>`

![изображение](https://github.com/URUWorks/TeroSubtitler/assets/105894506/551d106d-4124-48f9-85b5-ca7fa62a1ec7)

And this:

![изображение](https://github.com/URUWorks/TeroSubtitler/assets/105894506/e8944728-d946-4511-980d-479f587b0434)

Tero 1.0.0.6 is ok:

`  <Form Name="frmDelay" Caption="Set delay"/>`
`    </Form>  `
![изображение](https://github.com/URUWorks/TeroSubtitler/assets/105894506/fc277176-f5e4-440d-888c-315981fd6e30)

**Comment by URUWorks** [comment]
Since this form does not have children, it closes only with the ending "/>" on the same line, 
without the need to use </form>.
