### ISSUE TITLE
Project autoname

### ISSUE THREAD

**Issue by RoxMarty** [URUWorks/TeroSubtitler#132]
It would be great if the project name could be created automatically (based on the subtitle or video file name).

![изображение](https://github.com/URUWorks/TeroSubtitler/assets/105894506/1335849a-1d8e-4a5e-97b1-b58b4b1737a6)

Default value now is empty:
![изображение](https://github.com/URUWorks/TeroSubtitler/assets/105894506/dc63dfff-7204-4bb7-9e77-cc71fba62d53)

**Comment by URUWorks** [comment]
Fixed v1.0.0.8
