### ISSUE TITLE
Interface strings displayed truncated

### ISSUE THREAD

**Issue by GitGianluc** [URUWorks/TeroSubtitler#134]
**Describe the bug**
Since the size of the dialogue windows is not adjustable, long text strings within the interface get truncated.

**Steps to reproduce**
1. Launch Tero Subtitler.
2. Click on `New empty subtitle` on startup.
3. Go to `Tero Subtitler` > `Settings…` > `General` and set `Language` to `Italian - Italy`.
4. Close the dialogue, then go back to `Tero Subtitler` > `Impostazioni…` > `Convenzioni`: now you can see the text of the fourth line and of the last three lines truncated (as well as the fourth item of the side menu `Barre degli stru…`).

**Expected behaviour**
The user should be able to adjust the size of the dialogue windows according to the length of the text.

**Current behaviour**
The dialogue windows cannot be resized, causing the text that exceeds their size to be displayed truncated.

**Screenshots/Video**
<img width="784" alt="Tero_Text-truncated" src="https://github.com/URUWorks/TeroSubtitler/assets/16348719/bbdb97bb-12c9-469e-a22e-d36e44f8f47d">

**Info**
- MacBook Air M2 2022, running macOS Ventura 13.4.1 (c)
- Tero Subtitler 1.0.0.7

**Alternative solution**
Would it be possible to allow the interface text strings to wrap to the next line?

**Comment by URUWorks** [comment]
Improved v1.0.0.8

**Comment by GitGianluc** [comment]
To be honest, the issue is still visible in v1.0.0.8. I believe a definitive solution would be to make all dialogue windows resizeable by dragging.
