### ISSUE TITLE
Clicking on filter in Fix Subtitles should preview its findings

### ISSUE THREAD

**Issue by chenlung** [URUWorks/TeroSubtitler#14]
Regardless of tick status in Fix Subtitles, clicking on each filter (e.g. 'Break overlong lines) should list the entries affected (in case the user only wants the information).

Using Tero Subtitler alpha - Mac 10.11.6.

**Comment by URUWorks** [comment]
Something different has been implemented: numbers next to each filter to denote occurrences.
