### ISSUE TITLE
[macOS] Startup screen strings are not localised

### ISSUE THREAD

**Issue by GitGianluc** [URUWorks/TeroSubtitler#170]
**Describe the bug**
The text strings on the startup screen always appear in English even if a different language is selected for the interface.

**Steps to reproduce**
1. Launch Tero Subtitler.
2. Click on `New empty subtitle` on startup.
3. Go to `Tero Subtitler` > `Settings…` > `General` and set `Language` to `Italian - Italy`.
4. Quit Tero Subtitler and re-open it: the startup screen commands will still appear in English.

**Expected behaviour**
The startup screen should display the commands in the preselected language, as the translated strings are included in the configuration file.

**Current behaviour**
Some remnants of English strings are still displayed even if a different language is set for the application's interface.

**Info**
- MacBook Air M2 2022, running macOS Ventura 13.5.1
- Tero Subtitler 1.0.1.0

**Comment by URUWorks** [comment]
Correct, it is an error in the language file, it is from an old version or it was not updated correctly by the author 😄 
Try the following, open the file it-IT.xml with a text editor, and change the value: Count="40" to Count="41".

**Comment by GitGianluc** [comment]
@URUWorks The author of the file is incompetent! 😄
My fault, thank you for finding the error and suggesting a fix!
