### ISSUE TITLE
Each extension and format should be listed under unique entity in File Format list

### ISSUE THREAD

**Issue by chenlung** [URUWorks/TeroSubtitler#171]
**To Reproduce**
1. Open or save file
2. Click on the list of file formats

**Expected behaviour**
WebVTT has two entries, each representing the different extensions:
- WebVTT (*.vtt)
- WebVTT (*.webvtt)

**Current behaviour**
WebVTT has one entry, representing both extensions:
- WebVTT (*.vtt; *.webvtt)
![Each extension and format should be listed under unique entity in File Format list](https://github.com/URUWorks/TeroSubtitler/assets/2973439/2126cd88-3b03-4125-bf55-340cfef9bda1)

Notes:

- Also applies to JACOSub 2.7+
- LibreOffice 7.2.7.2 appears to exhibit the expected behaviour when saving:
![LibreOffice  file formats](https://github.com/URUWorks/TeroSubtitler/assets/2973439/7fcd0711-7497-4fb6-b1c3-8190413dbe4f)

**Desktop:**
 - OS: Mac 10.11.6
 - Version: 1.0.1.0

**Comment by URUWorks** [comment]
I'm not sure, in the example you give, it's because they are different versions, not the case for WebVTT.

**Comment by chenlung** [comment]
I'm wondering if Open and Save should be treated slightly differently?

Here is the Open from LibreOffice:
![LibreOffice  open](https://github.com/URUWorks/TeroSubtitler/assets/2973439/08d5970a-a657-4a9c-837f-99deca22df60)

The other problem I thought of, and one that also occurred to @GitGianluc, is the extension issue.
