### ISSUE TITLE
Change font-size of editor Text + Display Time to subtitles?

### ISSUE THREAD

**Issue by ankidoc** [URUWorks/TeroSubtitler#185]
**Is your feature request related to a problem? Please describe.**

First, what an awesome App, thanks so much! I create subtitels from mp4 via MacWhisper and then work with digital lectures to know what professors say so I don't have to go back a thousand times. 

I just wanted to know if there is any possibility to change the font-size or the Text which is provided by the .srt file and displayed (in my configuration) on the left side next to the videoplayer. Since I use it to quickly copy and paste, it's really hard to read since it's so small and I always have to use zoom function on MacOS.

+ when you hover over the timeline, the exact time of the spot it displayed. Is there any possibility that instead of this feature the actual time of the frame is displayed real time?

Thanks again!

**Comment by URUWorks** [comment]
Thanks, I understand the possibility of changing the text font, but I don't understand the other request, can you explain more?

**Comment by ankidoc** [comment]
Thanks for the fast reply! Does that mean that this feature will be implemented in the future?

here is a link of what I mean:
https://share.cleanshot.com/qD9GY5twPyS4pNpfFf0Z
So basically: when you hover of the timeline, the exact time of the position where the mouse is gets displayed, and it disappears when the mouse is leaving the timeline area. I just wanted to know if it is possible to display the current time instead permamently in this position, but now I noticed, that it is in the right lower corner, but way smaller.

But I had another idea. What about a shortcut that triggers copying the current position (timestamp) to the clipboard? I often use timestamps so that I can jump right to the position if I have to again listen to certain explanations. Or is there already a function like that?

Greetings

**Comment by URUWorks** [comment]
Correct, both requests will be implemented 😃 
Thanks

**Comment by ankidoc** [comment]
woaaah that's awesome and really made my day, thanks! I'm new to github. Is there a possibility I can subscribe to this app so I get notified, when you upload a new release with the features?

and another question: Before using your app I worked with IINA. The MacOS function Key F8 (Play/pause) did trigger the play/pause effect. But it seems that it is not triggering the Play/pause effect in Tero Subtiteler. Is there anything I can do to make that work?

Again, thanks a lot!

**Comment by URUWorks** [comment]
You can try assign the "Play/Pause" shortcut to "F8" from settings ?

**Comment by ankidoc** [comment]
hello!
yeah that works, but only when the window is focused. Since I'm generally writing stuff in the flashcard app, hitting F8 then does not play/pause the content played in the Tero subtiteler.

**Comment by URUWorks** [comment]
` What about a shortcut that triggers copying the current position (timestamp) to the clipboard?`

milliseconds? 


`yeah that works, but only when the window is focused. Since I'm generally writing stuff in the flashcard app, hitting F8 then does not play/pause the content played in the Tero subtiteler.`

I'm going to investigate how those keys work in macOS.

**Comment by ankidoc** [comment]
hello!

I guess the hh:mm:ss would absolutely suffice if that's what you're meaning

Thanks for investigating. Programs that works with theys keys include apple music, media players like iina.
I think one of the reasons might be that on apple you have the "now playing" option in the menu bar, which displays the active media file (like mp4 oder mp3). And I think when this is "recognized", the play/pause and "next" buttons work

![_mcjvRl39](https://github.com/URUWorks/TeroSubtitler/assets/81517565/3b1e9f0e-42bc-4e2f-a185-56a8f6cd9212)

**Comment by URUWorks** [comment]
Main request was implemented in v1.0.1.2, for "Multimedia keys" or others, please open another request.
