### ISSUE TITLE
Trying to use Faster-whisper

### ISSUE THREAD

**Issue by Brissinger** [URUWorks/TeroSubtitler#191]
Standard Whisper works as usual. Meantime, at least for me, while trying to transcribe with faster-whisper it shuts down after 3 seconds (any model). 
Latest TeroSubtitler installed, Win11, Ryzen 5 3600, Rtx 3060, 24GB Ram

**Comment by URUWorks** [comment]
Can you try this version and let me know?

[terosubtitler_testbuild_win64.zip](https://github.com/URUWorks/additional-files/raw/main/terosubtitler_testbuild_win64.zip)

**Comment by Brissinger** [comment]
Ok so i tried and that's what I observed. It runs for a little longer (up to around 20 s) but then it shuts again like before. Here is the log from command prompt. It seems to be missing CUDA dll.
[TSTtero.exeLOG.txt](https://github.com/URUWorks/TeroSubtitler/files/13196464/TSTtero.exeLOG.txt)

**Comment by RoxMarty** [comment]
> Meantime, at least for me, while trying to transcribe with faster-whisper it shuts down after 3 seconds (any model).
Maybe you also (like me) have a Nvidea video card and fast processing in CUDA mode doesn't work (i.e. it only works on the CPU)? In that case, I solved this problem by using this version of faster-whisper:
https://github.com/Purfview/whisper-standalone-win/releases?q=&expanded=true
This version is work for me:  Whisper-Faster_r153.zip (not r160)

You must download it [from here](https://github.com/Purfview/whisper-standalone-win/releases/download/faster-whisper/Whisper-Faster_r153.zip)
Also download [ cuBLAS.and.cuDNN.7z ](https://github.com/Purfview/whisper-standalone-win/releases/download/libs/cuBLAS.and.cuDNN.7z) and put them together in one folder

Then you need to specify the path to that directory with Whisper-Faster in Tero Subtitler.
And everything will be fine

**Comment by Brissinger** [comment]
Yea it works aith nvidia libraries pasted in whisper folder.
