### ISSUE TITLE
Whisper.cpp and Faster-Whisper on Mac (arm)

### ISSUE THREAD

**Issue by retteghy** [URUWorks/TeroSubtitler#193]
**Is your feature request related to a problem? Please describe.**
Whisper.cpp and Faster-Whisper failed to download when I first launched Tero, now I can still set them up under Settings/Tools, but I am not sure where to download them from.  

**Describe the solution you'd like**
Links for the 3rd party tools (under Settings/Tools). Ideally the names of the 3rd party tools should be hyperlinks. Less ideally there should be some info there what file the program is expecting exactly. 

**Describe alternatives you've considered**
I found Whisper.cpp and Faster-Whisper on github, but only the source code is available, no Mac binaries. 

**Additional context**
Macbook Air M1 running Sonoma 14.1. Terosubtitler 1.0.1.2 (x86_64 via Rosetta 2)

<img width="715" alt="Screenshot 2023-10-29 at 08 56 26" src="https://github.com/URUWorks/TeroSubtitler/assets/7005706/11d3ca67-c347-4dc5-b2ab-42f93868b9c7">
.

**Comment by retteghy** [comment]
I managed to reset the app by deleting all preference files and folders it created and reinstalling it. Upon first launch it again shows the "Getting started wizard", but I again failed to download both versions of whisper. Any help would be appreciated. If I'd know what files your program is looking for, I could try to compile them myself.

**Comment by URUWorks** [comment]
I don't have a way to test it in arm, but you can try this version:

[terosubtitler_testbuild_macOS64](https://github.com/URUWorks/additional-files/raw/main/terosubtitler_testbuild_macOS64.dmg)

The files used in this latest version are:

[fasterwhisper_x86_64](https://github.com/URUWorks/additional-files/raw/main/whisper/fasterwhisper_x86_64.zip)
[whisper_macOS_x86_64](https://github.com/URUWorks/additional-files/raw/main/whisper/whisper_macOS_x86_64.zip)

You must unzip it in a folder and configure the path in Tero settings.

**Comment by GitGianluc** [comment]
@URUWorks Faster Whisper doesn't work for me either…
I've downloaded [this file](whisper/fasterwhisper_arm64.zip), unpacked in Tero’s main folder, updated the relevant path in Settings (`~/tero/Whisper/whisper-faster`), but after 3 seconds it shuts down.
Should I compile the `whisper-faster` file to get an executable? Taken “as is”, it has no file format…

**Info**
> MacBook Air M2 2022, running macOS Ventura 13.6
> Tero Subtitler 1.0.1.2

**Comment by GitGianluc** [comment]
@retteghy Whisper.cpp is already compiled for ARM64: you can try [this file](whisper/whisper_macOS_arm64.zip) out.

@URUWorks  
> [whisper_macOS_x86_64](https://github.com/URUWorks/additional-files/raw/main/whisper/whisper_macOS_x86_64.zip)

This file works for Intel Macs!

**Comment by URUWorks** [comment]
Currently Purfview does not have a compiled version for ARM64

**Comment by GitGianluc** [comment]
@URUWorks I managed to get Faster-Whisper working with the latest test build, but it's much slower than Whisper.cpp on Apple Silicon M1/M2 because the product is optimized for Windows and nVIDIA GPUs. After some further investigation, I've determined that the only faster version of Whisper compatible with ARM64 architectures is [Whisper CTranslate2](https://github.com/Softcatala/whisper-ctranslate2#cpu-and-gpu-support).

**Comment by URUWorks** [comment]
You would have to ask Purfview about GPU support in macOS, and if there is a chance of compiling it for ARM64.
