### ISSUE TITLE
Default adjustment to time via directional arrows applies to hour

### ISSUE THREAD

**Issue by chenlung** [URUWorks/TeroSubtitler#20]
https://github.com/URUWorks/TeroSubtitler/assets/2973439/c6b6261c-40db-4cee-86cd-0664031627d5

Unless hour, minute, or second is selected or clicked, clicking either directional button should adjust frames/milliseconds by default (i.e. when nothing is selected).

Using Tero Subtitler alpha - Mac 10.11.6.

**Comment by URUWorks** [comment]
Fixed v1.0.0.1
