### ISSUE TITLE
Adjust subtitle function (Alt+L) - improved functionality

### ISSUE THREAD

**Issue by mhendu** [URUWorks/TeroSubtitler#203]
Maybe I'm not using this feature correctly, but it's difficult to work with. It's fine if you want to just do an adjustment of start and end time, to account for a simple frame rate correction, but more complex adjustments are difficult. In the current version if you want to use the advanced feature you have to remember for each subtitle what change you want to make to the timecode, and you can't progress the video to check your timing, and the dialog box doesn't remember your adjustments when you close it.

It would be better if you could make these adjustments while on the main screen so you could go between each subtitle and make timing tweaks while confirming sync vs the video player, then do a calculated adjustment to the remaining subtitles based on the changes that had been made up to that point.

**Comment by URUWorks** [comment]
Understood, we will work on improving this function :)
