### ISSUE TITLE
OCR regex \x22 is not being replaced

### ISSUE THREAD

**Issue by spacekomet** [URUWorks/TeroSubtitler#205]
After implementing #198 , also other ocr files, besides Default.ocr, are being checked. Thanks.

However I've noticed an issue with not finding string \x22. 

For example:

Subtitle text: 
\x22\x22

Ocr rule:
`{
	"OCR" :[
		{"Find" : "(\\x22){2,}", "ReplaceBy" : "\\x22", "UseRE" : "1"},
	]
}`

It should change text to \x22  , but it doesn't find anything. 
It's working with https://regex101.com/ and also with a small test fpc program I put together using the  same function  ReplaceRegExpr  as part of TRegExpr library.

At first I thought it's a problem with escape character, but this rule, as an example, is ok:
{"Find" : "\\b(0)[A-Za-z]", "ReplaceBy" : "O", "UseRE" : "1"},

Could it be that Json parser is having problem with the \x ?
Or do you perhaps have a workaround? Could be I'm using wrong settings for the rule.

Thank you

**Comment by URUWorks** [comment]
Hola,

`{ "OCR" :[ {"Find" : "(\\\\x22){2}", "ReplaceBy" : "\\\\x22", "UseRE" : "1"}, ] }`

Maybe?

**Comment by spacekomet** [comment]
Ah, yes it works like that, thanks again :). 

I thought we can take accompanied OCR files as a reference, but it seems they have wrong regex rules in there. For above example, not only extra slashes are missing, but also round brackets and without the brackets it also doesn't work. 

My goal is to convert old SW rules for my  language into the new format, however it presents somewhat a challenge, because of those quirks  you cannot simply copy paste the old rule. 

Btw: I guess it's not possible to have comments in the json OCR file, like in the old SW OCR file, right? Especially with regex it always helps to have a description what the rule is actually doing. 

Thank you

**Comment by URUWorks** [comment]
JSON does not support comments :(
Anyway, your conversions and/or corrections are welcome.
