### ISSUE TITLE
No GPU use in latest version of faster

### ISSUE THREAD

**Issue by johnfelipe** [URUWorks/TeroSubtitler#207]
https://github.com/URUWorks/TeroSubtitler/discussions/204#discussioncomment-7635741

I think disscussion is not view

https://github.com/URUWorks/TeroSubtitler/assets/428820/c58f19a4-b6a3-4c14-a213-39bb03079ea2

**Comment by Purfview** [comment]
What error do you get?

**Comment by johnfelipe** [comment]
> What error do you get?

can u share me CUDA v11.x for windows 10 64 bits pls, for not shoot to another missed file

**Comment by Purfview** [comment]
https://github.com/Purfview/whisper-standalone-win/releases/tag/libs

**Comment by johnfelipe** [comment]
[cuBLAS.and.cuDNN_win_v3.zip](https://github.com/Purfview/whisper-standalone-win/releases/download/libs/cuBLAS.and.cuDNN_win_v3.zip)

that then cover GPU execution requires CUDA v11.x and cuBLAS and cuDNN libs?

**Comment by Purfview** [comment]
yes

**Comment by johnfelipe** [comment]
sorry, but where path in folder need to put this dll?

**Comment by Purfview** [comment]
In the same folder as exe, anyway Tero Subtitler should've done that for you automatically.

I just looked at your video, there is no error. It works on GPU!

**Comment by johnfelipe** [comment]
![SNAG-0240](https://github.com/URUWorks/TeroSubtitler/assets/428820/3515ac01-a0a2-4a3a-8e40-634a859730f4)

that GPU is not supported may be?

**Comment by johnfelipe** [comment]
![SNAG-0241](https://github.com/URUWorks/TeroSubtitler/assets/428820/faab0d97-991f-4a16-a519-5678300feff1)

not make sense for a video with 4 min take to long time for have transcribe?

**Comment by Purfview** [comment]
> that GPU is not supported may be?

Only you can know. It doesn't support older than Kepler chips.
Even if it supports you would be able to use maximum the small model.

**Comment by Purfview** [comment]
> not make sense for a video with 4 min take to long time for have transcribe?

I dunno what TS does.
Use faster-whisper directly to see what's going on.

**Comment by johnfelipe** [comment]
![SNAG-0242](https://github.com/URUWorks/TeroSubtitler/assets/428820/f84efcf5-1505-4dac-83ae-aad298db254c)

redownloading model...

**Comment by Purfview** [comment]
There is no point in redownloading models.... Use faster-whisper directly to see what's going on.

OK, I'm out of here, good luck!

**Comment by johnfelipe** [comment]
How use directly, I don't understand, can u share me instructions, sorry
for rookie question

**Comment by URUWorks** [comment]
> I just looked at your video, there is no error. It works on GPU!
