### ISSUE TITLE
Unbreak lines wrong when new line starts with a dash.

### ISSUE THREAD

**Issue by CM630** [URUWorks/TeroSubtitler#216]
**Describe the bug**
Unbreak lines wrong when new line starts with a dash.

**To Reproduce**
1. Load subs.
2. Select a few lines.
3. Go to Menu/Edit/Texts/Unbreak subtitles

**Expected behavior**
Lines starting with a dash shall **not** be unbroaken, because the dash indicates, that another person is speaking.

**Current behavior**
All lines are unbroken, including the ones starting with a dash.

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: All
 - Version 1.0.1.13

**Additional context**
Here is a fix:

in the Common package in file UWSubtitles.Utils.pas replace 
`   function UnbreakSubtitles(const Text: String; const BreakChar: String = sLineBreak): String;...`
 
with 
```
function UnbreakSubtitles(const Text: String; const BreakChar: String = sLineBreak): String;
var
  AllLines: array of string;
  Line : integer = 0;
begin
  if pos(BreakChar,Text) = 0
    then exit (Text);
  if pos('-',Text) = 0
    then exit(ReplaceString(Text, BreakChar, ' '));
  AllLines:=  Text.Split([BreakChar]);
  Result := AllLines[0];
  for Line := 1 to high(AllLines) do
    if UTF8LeftStr(AllLines[Line],1)= '-'
      then Result := Result + BreakChar + AllLines[Line]
      else Result := Result + ' ' + AllLines[Line];
end;
```

**Comment by URUWorks** [comment]
Fixed! Thanks
