### ISSUE TITLE
Crash after changing the divider size

### ISSUE THREAD

**Issue by ankidoc** [URUWorks/TeroSubtitler#217]
I was using the tool for my lectures. Since the content does not adapt to the width of divider between text and video with subtitles, I'll often have to shift it to the right so the whole text of the sentence or passage becomes visible. This often results in crashes.

Using a MBP 2023 M2 pro 16 gb
Using MacOS Ventura latest version macOS Ventura 13.6.2
Using Tero last build from November (screenshot) 1.0.1.3

 
![_5H5gRrWv](https://github.com/URUWorks/TeroSubtitler/assets/81517565/0803934f-4f48-4e34-9217-71508b046ab3)

![_jaMFh02a](https://github.com/URUWorks/TeroSubtitler/assets/81517565/f9d7b26b-ee93-42bf-83c7-8dbfce9636e9)

Thanks!

**Comment by chenlung** [comment]
Could you edit your post to include the specific version and OS, please?

**Comment by URUWorks** [comment]
Can you specify if it is always and with(out) a video loaded?
on my macOS Monterey system it is working correctly.

![test](https://github.com/URUWorks/TeroSubtitler/assets/19515662/011a5b97-55ef-4f46-a2db-7b0808caa1ad)

**Comment by ankidoc** [comment]
> Can you specify if it is always and with(out) a video loaded? on my macOS Monterey system it is working correctly.
> 
> ![test](https://private-user-images.githubusercontent.com/19515662/292670543-011a5b97-55ef-4f46-a2db-7b0808caa1ad.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0MzEyOTksIm5iZiI6MTcwMzQzMDk5OSwicGF0aCI6Ii8xOTUxNTY2Mi8yOTI2NzA1NDMtMDExYTViOTctNTVlZi00ZjQ2LWEyZGItN2IwODA4Y2FhMWFkLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI0VDE1MTYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0MmQxNGRmOTU2MDkzN2FkNzE4ZDM2ODI0MmIwNjE2MzFkMzI4NDU2ZmNiN2ZmYmFlYTZlOTM4YmU2ZjI0Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MH9f8Erk_8hv1JGNWWaDCzXojz4hUPv9sksMijBXXaQ) [ ![test](https://private-user-images.githubusercontent.com/19515662/292670543-011a5b97-55ef-4f46-a2db-7b0808caa1ad.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0MzEyOTksIm5iZiI6MTcwMzQzMDk5OSwicGF0aCI6Ii8xOTUxNTY2Mi8yOTI2NzA1NDMtMDExYTViOTctNTVlZi00ZjQ2LWEyZGItN2IwODA4Y2FhMWFkLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI0VDE1MTYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0MmQxNGRmOTU2MDkzN2FkNzE4ZDM2ODI0MmIwNjE2MzFkMzI4NDU2ZmNiN2ZmYmFlYTZlOTM4YmU2ZjI0Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MH9f8Erk_8hv1JGNWWaDCzXojz4hUPv9sksMijBXXaQ) ](https://private-user-images.githubusercontent.com/19515662/292670543-011a5b97-55ef-4f46-a2db-7b0808caa1ad.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0MzEyOTksIm5iZiI6MTcwMzQzMDk5OSwicGF0aCI6Ii8xOTUxNTY2Mi8yOTI2NzA1NDMtMDExYTViOTctNTVlZi00ZjQ2LWEyZGItN2IwODA4Y2FhMWFkLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI0VDE1MTYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0MmQxNGRmOTU2MDkzN2FkNzE4ZDM2ODI0MmIwNjE2MzFkMzI4NDU2ZmNiN2ZmYmFlYTZlOTM4YmU2ZjI0Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MH9f8Erk_8hv1JGNWWaDCzXojz4hUPv9sksMijBXXaQ) [ ](https://private-user-images.githubusercontent.com/19515662/292670543-011a5b97-55ef-4f46-a2db-7b0808caa1ad.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0MzEyOTksIm5iZiI6MTcwMzQzMDk5OSwicGF0aCI6Ii8xOTUxNTY2Mi8yOTI2NzA1NDMtMDExYTViOTctNTVlZi00ZjQ2LWEyZGItN2IwODA4Y2FhMWFkLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI0VDE1MTYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0MmQxNGRmOTU2MDkzN2FkNzE4ZDM2ODI0MmIwNjE2MzFkMzI4NDU2ZmNiN2ZmYmFlYTZlOTM4YmU2ZjI0Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MH9f8Erk_8hv1JGNWWaDCzXojz4hUPv9sksMijBXXaQ)

it actually only happens when a video is loaded and the fitting sutbtitle svt, but it is not depend on which video is loaded. But they are all quite big files, at least the .mp4 data contains 1+ hour. The svt was made with mac whisper.

**Comment by chenlung** [comment]
Could you upload the following, please, @ankidoc:
- Video (somewhere else if too big, with a link provided via Discord — perhaps privately) and subtitle file
- Screencast

**Comment by chenlung** [comment]
No further information provided.

Please reopen if still reproducible and with the material required for others to do so.

**Comment by URUWorks** [comment]
Possibly fixed in v1.0.1.6.

**Comment by ankidoc** [comment]
Hello! Sry I did not see your request. But wanted to check if the problem still persist and download the new version. On github I couldn't find new versions, and on the website I get an error message with the website being empty after confirmation.

![_Safari-URUWorks---21 01 2024---11 05 18](https://github.com/URUWorks/TeroSubtitler/assets/81517565/a5b26356-f573-4b49-abc6-67b241e2aa65)

**Comment by URUWorks** [comment]
Of course, you can download here:

https://github.com/URUWorks/additional-files/raw/main/terosubtitler_testbuild_macOS64.zip
