### ISSUE TITLE
TTS using elevenlabsTTS for dubbing feature 

### ISSUE THREAD

**Issue by johnfelipe** [URUWorks/TeroSubtitler#232]
https://drive.google.com/file/d/1u9_0IH3HHbmn9YiuXEaA92ZIOYAjYsw4/view?usp=sharing

There is an example using https://github.com/jianchang512/pyvideotrans

pls tell me if is interesting for add in roadmap?

**Comment by URUWorks** [comment]
yes, very interesting

**Comment by johnfelipe** [comment]
When will be avaible?
Dubbed will be with elevenlabs?
