### ISSUE TITLE
crash with latest v3 faster

### ISSUE THREAD

**Issue by johnfelipe** [URUWorks/TeroSubtitler#233]
https://github.com/URUWorks/TeroSubtitler/assets/428820/18aa5253-3fe5-4ea7-b251-8080f86a0e1f

one minute later crash and not show subtitles

**Comment by chenlung** [comment]
Does Tero generate a crash log? Are you sure it's crashing? I'm wondering if it's [this](https://github.com/URUWorks/TeroSubtitler/discussions/67) you're encountering.

**Comment by johnfelipe** [comment]
how can debug this?
path to crash log?

**Comment by johnfelipe** [comment]
i upload to latest version and still not works - portable version

crash in 30 sec


https://github.com/URUWorks/TeroSubtitler/assets/428820/ee0154e0-80b2-46ec-9c1e-0593c0d44075

**Comment by URUWorks** [comment]
¿Sucede con todos los modelos o solo con v3?

**Comment by Purfview** [comment]
> crash in 30 sec
> SNAG-0035.mp4

That model is for some old version, it shouldn't work in the newer versions.

**Comment by johnfelipe** [comment]
With app, not download correctly, can u tell me where can download?

**Comment by Purfview** [comment]
> With app, not download correctly, can u tell me where can download?

No idea what you mean.
All info is in my repo.

**Comment by johnfelipe** [comment]
im talking about TERO not your repo bro
with TERO not download v3 files, where can download manually?

**Comment by Purfview** [comment]
I don't know anything about "TERO", so I can't answer questions about it.

**Comment by URUWorks** [comment]
Can be downloaded manually from: https://huggingface.co/Systran

**Comment by URUWorks** [comment]
wrong model was used.
