### ISSUE TITLE
GUI improvements - More space in Settings and increase string width

### ISSUE THREAD

**Issue by bovirus** [URUWorks/TeroSubtitler#253]
@URUWorks 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Please check screenshots

Increase width of Settings window on the right
Increase text widths if possible
Increase input box width

![TeroSubititle - 01a - original](https://github.com/URUWorks/TeroSubtitler/assets/1262554/2bcc3fa0-3e37-4440-a5eb-7fc45897f224)
**original**

![TeroSubititle - 01b - revised](https://github.com/URUWorks/TeroSubtitler/assets/1262554/c255d029-509a-4e82-9993-06ed8300c4f7)
**Proposal**

![TeroSubititle - 02a - original](https://github.com/URUWorks/TeroSubtitler/assets/1262554/7d599e30-cb61-497c-a81f-635968e64266)
**Original**

![TeroSubititle - 02ab- revised](https://github.com/URUWorks/TeroSubtitler/assets/1262554/d3f70f25-fbdc-41b9-b0e0-9f692155e7e2)
**Proposal**

![TeroSubititle - 03a - original](https://github.com/URUWorks/TeroSubtitler/assets/1262554/e291ad7e-b104-45be-b911-28ccfb0a681e)
**Original**

![TeroSubititle - 03b - revised](https://github.com/URUWorks/TeroSubtitler/assets/1262554/2df26006-858f-49cc-91fb-f87479e309cd)
**Proposal**

![TeroSubititle - 04](https://github.com/URUWorks/TeroSubtitler/assets/1262554/bc117324-2c74-4492-aa64-6dcdabd7883b)
**Add "Shift" string to language file ("Maiusc" in italian)**

**Describe alternatives you've considered**

**Additional context**

**Comment by URUWorks** [comment]
https://github.com/URUWorks/additional-files/raw/main/terosubtitler_testbuild_win64.zip

**Comment by bovirus** [comment]
@URUWorks 

Thanks for new beta.
erfect.
Some feedback. 
Please check screenshot and prposal for strings

![image](https://github.com/URUWorks/TeroSubtitler/assets/1262554/f7a10d14-4ae1-4aac-afff-e32919ca86ee)
original

![image](https://github.com/URUWorks/TeroSubtitler/assets/1262554/2a630a24-2eb5-4c03-a7ce-4ef4386462f1)
My proposal applied

About the window that appear when you close without saving a file now you using two strings

File has not been saved.

and


“%s”
Do you wish to save it?**

I propsaoe to use  a single specifc string

The following file

“%s”

has not been saved. Do you wish to save it?

**Comment by bovirus** [comment]
@URUWorks 

Should I complete tarnslationof 'lclstrconsts.it.po' language file?
