### ISSUE TITLE
Conventions: count space characters

### ISSUE THREAD

**Issue by chenlung** [URUWorks/TeroSubtitler#26]
There is a [question](https://partnerhelp.netflixstudios.com/hc/en-us/articles/115001352212-How-is-reading-speed-measured-Do-punctuation-and-spaces-count-) in the FAQ section of Netflix's Partner Help Center:

> How is reading speed measured? Do punctuation and spaces count?

_Our internal software (as many others in the industry) calculates reading speed in characters per second. We calculate reading speed for each individual subtitle event as well as the average reading speed of the file._

_Spaces and punctuation are counted by the software towards both the character count and the reading speed limit. For single-byte (half width) characters for character-based languages, punctuation and Latin characters count as 0.5 character, unless specified otherwise in the language Style Guide._

I believe I was once informed that spaces are counted, but it might be wise to add this as an option (also in making it clearer), enabling it for the Netflix profiles (at least) in Conventions.

Using Tero Subtitler alpha - Mac 10.11.6.

**Comment by chenlung** [comment]
For the public alpha (1.0.0.0), there is a blank box next to Characters per Second called Characters to Ignore (tooltip).

I propose that Characters to Ignore be placed below Characters per Second (as a setting in its own right) and titled 'Characters excluded from CPS count'.

**Comment by URUWorks** [comment]
Changed v1.0.0.4
