### ISSUE TITLE
Error on saving custom shortcut

### ISSUE THREAD

**Issue by andreamilani82** [URUWorks/TeroSubtitler#260]
**Describe the bug**
If I try to add some shortcut by Edit > Settings > Shortcut window, I get an alert saying "List index (-1) out of bounds" when saving.
After that, new shortcuts aren't stored

**To Reproduce**
1. Go to 'Edit' then "Settings" Then "Shortcut"
2. Choose category "Timings"
3. Choose "Edit initial frame" and, after click in "shortcut" field, press Ctrl + F10
4. Click "Close"
5. See error

**Expected behavior**
I expect to be able to setting custom shortcuts

**Current behavior**
It gives error on closing window

**Screenshots/Video**
See attach
<img width="276" alt="Immagine1" src="https://github.com/URUWorks/TeroSubtitler/assets/160515910/6bfda299-ed54-4d2d-b9f6-ebbf026bb0f8">

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 1.0.1.6

**Additional context**

**Comment by URUWorks** [comment]
https://github.com/URUWorks/additional-files/raw/main/terosubtitler_testbuild_win64.zip

Can you check if it works correctly?

**Comment by andreamilani82** [comment]
It works, thanks!

Da: URUWorks ***@***.***>
Inviato: lunedì 19 febbraio 2024 23:59
A: URUWorks/TeroSubtitler ***@***.***>
Cc: Andrea Milani ***@***.***>; Author ***@***.***>
Oggetto: Re: [URUWorks/TeroSubtitler] Error on saving custom shortcut (Issue #260)


https://github.com/URUWorks/additional-files/raw/main/terosubtitler_testbuild_win64.zip

Can you check if it works correctly?
