### ISSUE TITLE
Access violation

### ISSUE THREAD

**Issue by andreamilani82** [URUWorks/TeroSubtitler#266]
**Describe the bug**
On startup, an alert appear (see attach)
![2024-02-22 17_33_36-New Issue · URUWorks_TeroSubtitler – Mozilla Firefox](https://github.com/URUWorks/TeroSubtitler/assets/160515910/92bcce8f-c760-413e-99de-81c7ce71e00a)

If I click on "OK", the software starts but the alert appears again at any move.

Strangely, this alert appears suddenly: I've used Tero all day without problems.

The alert appears even after a reboot.

**To Reproduce**
1. Just opening the software

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 1.0.1.7

**Comment by URUWorks** [comment]
You are correct, it is because of the empty shortcuts file. 
The strange thing is because it's empty :S

Please try the updated testbuild:
https://github.com/URUWorks/additional-files/raw/main/terosubtitler_testbuild_win64.zip
