### ISSUE TITLE
error message everytime I want to change anything in the settings

### ISSUE THREAD

**Issue by ankidoc** [URUWorks/TeroSubtitler#267]
**Describe the bug**

Anything that can be change triggers the same error message which leads to quitting the app.

**To Reproduce**
open settings, change anything, click close, error message pops up

**Expected behavior**
changes are accepted and window closes

**Current behavior**
error message pops up

**Screenshots/Video**
![_Tero Subtitler-Settings---23 02 2024---14 37 46](https://github.com/URUWorks/TeroSubtitler/assets/81517565/cf93dff6-4b28-4443-91ef-3d44831c5cc4)

**Desktop (please complete the following information):**
 - OS: [MacOS 14.3.1 (23D60)]
 - version 1.0.1.6

**Additional context**
tried clean uninstall and reinstall, did not change anything
the same problem happens with version 1.0.1.5

**Comment by URUWorks** [comment]
Hello, theoretically this bug was fixed in the testbuild. 
Can you try it and confirm for us?

https://github.com/URUWorks/additional-files/raw/main/terosubtitler_testbuild_macOS64.zip

Thank you!
