### ISSUE TITLE
Toolbar: don't allow buttons to encroach others when repositioning

### ISSUE THREAD

**Issue by chenlung** [URUWorks/TeroSubtitler#27]
https://github.com/URUWorks/TeroSubtitler/assets/2973439/1e139b93-1b09-47c0-9824-09f1184ee532

It's possible to drag sections of buttons and have them encroach others.

Using Tero Subtitler alpha - Mac 10.11.6.

**Comment by URUWorks** [comment]
v1.0.1.7
