### ISSUE TITLE
Crash error on Settings exit

### ISSUE THREAD

**Issue by Brissinger** [URUWorks/TeroSubtitler#271]
Crash error while closing settings with Close button.
Latest TeroSubtitler installed, Win11, Ryzen 5 3600, Rtx 3060, 24GB Ram
![Zrzut ekranu 2024-02-24 165004](https://github.com/URUWorks/TeroSubtitler/assets/72404411/ac1fffe5-cf54-4b10-830f-2689ed60e8fa)

**Comment by URUWorks** [comment]
Hello, theoretically this bug was fixed in the testbuild.
Can you try it and confirm for us?

https://github.com/URUWorks/additional-files/raw/main/terosubtitler_testbuild_macOS64.zip

Thank you!

**Comment by Brissinger** [comment]
I would need Windows version :)

**Comment by URUWorks** [comment]
https://github.com/URUWorks/additional-files/raw/main/terosubtitler_testbuild_win64.zip :)

**Comment by Brissinger** [comment]
Yea, it's gone.
