### ISSUE TITLE
Set pauses for the whole file

### ISSUE THREAD

**Issue by bggeorgieva** [URUWorks/TeroSubtitler#276]
I am usually using Subtitle Workshop on my Windows PC.
Now that I'm on Mac, I finally found this and I see how improved it is.
But one of the main features that I am using for every single file I open, is "Set Pauses" under the "Edit-> Timings"

Is there a way to set pauses for the whole file?

**Comment by chenlung** [comment]
Are you referring to gapping between subtitle entries?

**Comment by bggeorgieva** [comment]
Yes, in this version you call it "gap".
This is what I see in Subtitle Workshop
![Screenshot_20240228_194357_Microsoft Remote Desktop](https://github.com/URUWorks/TeroSubtitler/assets/16948583/930c8ed4-8f4b-44db-819b-0b9370b6e939)

**Comment by chenlung** [comment]
You can choose it in Settings>Conventions.

**Comment by bggeorgieva** [comment]
Do you have a documentation somewhere what in SW corresponds to what in TS?
It's very difficult and very different.
In SW I had coloring for whole rows in different colors depending on the mistake.
How to find that in TS?
I am sending you a refference of how my settings look like in SW. I've tried to make them in TS, but some of the things are not there.
Also, the high CpS in SW is added as %, here is just showing in red and Idk how much % this is.
Are there things deprecated along the way or is it just me not being able to find some of the settings?

My settings: https://docs.google.com/document/d/1o8rlmjug2OSgglglukz6c4Nu1cyTt71GvJ1FGVbQMY0/edit?usp=drivesdk

**Comment by chenlung** [comment]
I believe there are two Subtitle Workshops, and I only used one of them a long time ago (possibly not the one involving URUWorks?).

I think @URUWorks is best placed to answer.

**Comment by URUWorks** [comment]
added, please try the testbuild:

https://github.com/URUWorks/additional-files/raw/main/terosubtitler_testbuild_win64.zip
