### ISSUE TITLE
Interface Italian - Bottom info set as English

### ISSUE THREAD

**Issue by bovirus** [URUWorks/TeroSubtitler#298]
@URUWorks 

**Describe the bug**
Please check screenshot
GUis et as Italian on first configuration
Bootom indicator report English and not Italian aas expected

**To Reproduce**
1. Set Ityalian language

**Expected behavior**
Italian GUI - Italian as bottom indicator

**Current behavior**
See screenshot

**Screenshots/Video**

**Desktop (please complete the following information):**
 - OS: Windo2s 11 22H2 64bit Italian
 - Version 1.0.1.8

**Additional context**

![image](https://github.com/URUWorks/TeroSubtitler/assets/1262554/ce09b309-5f06-4a40-818c-a5989731fdfe)

**Comment by URUWorks** [comment]
In the status bar, what is shown is the dictionary language, not the interface :)

**Comment by bovirus** [comment]
@URUWorks 

The dictionarry should follow up the GUI setting (if the dictionary is available).
If I select Italian as GUI language the default dictionarry should be "Italian".

**Comment by chenlung** [comment]
It's a good question whether to revert to the dictionary's language upon a change of the GUI. What do other applications do (e.g. LibreOffice)?

These are my thoughts:
- What if there is no dictionary for that language?
- What if you are an Italian operator who prefers the Italian GUI but is working on English subtitles?

**Comment by bovirus** [comment]
My request is about first setting after installation.
If I select Italian language for installation and Itlian dictiorary is availble set Italian language by default.

About your request

If the dictionary that matcg GUI langauge is not avilabel set English dictionary.

Most italian user prefer by default Italian language/dictionary set as default.
If an Italian user want to change the dictionary can do that after installation (I belkieve that could be very rare).

**Comment by URUWorks** [comment]
Well, we'll do that by choosing the language in the Wizard.
