### ISSUE TITLE
[macOS – ARM64] Damaged (or missing?) library on startup

### ISSUE THREAD

**Issue by GitGianluc** [URUWorks/TeroSubtitler#302]
**Describe the bug**
At program startup, a warning message appears: 

> “libmpv.2.dylib” is damaged and can’t be opened. You should move it to the Trash.

**To Reproduce**
1. Launch **Tero Subtitler 1.0.1.8**
2. The warning message is displayed

**Expected behavior**
No warning message is expected.

**Screenshots/Video**
<img width="404" alt="libmpv2-issue" src="https://github.com/URUWorks/TeroSubtitler/assets/16348719/6f8111c1-5e5a-4ff3-8f54-cb1438c0076c">

**Environment:**
 - MacBook Air M2 (2022), running macOS Ventura 13.6.6
 - Tero Subtitler version: 1.0.1.8

**Additional context**
Note that the issue arises only with the current version, but it was not present up to version 1.0.1.7.

**Comment by URUWorks** [comment]
I would obey and move it to the trash 😂
After that does Tero start?

**Comment by GitGianluc** [comment]
Yes, it does. But I remember – going back to Subtitle Workshop – that libmpv2 used to be (or still is?) an essential component. Should I throw it in the bin?

**Comment by URUWorks** [comment]
I don't remember it being necessary in SW and even less if it is corrupt :)
