### ISSUE TITLE
ERROR ffmpeg.exe dubbing video with elevenlabs

### ISSUE THREAD

**Issue by johnfelipe** [URUWorks/TeroSubtitler#305]
![SNAG-0117](https://github.com/URUWorks/TeroSubtitler/assets/428820/243a4631-b075-4a2a-bba2-f74f0ca19e96)

that will cost a lot of Character Usage

**Comment by johnfelipe** [comment]
Already fixed?

**Comment by URUWorks** [comment]
Can you try this version and tell me if it works for you?

https://github.com/URUWorks/additional-files/raw/main/terosubtitler_testbuild_win64.zip
