### ISSUE TITLE
letter trimming of italic subtitles in Turkish

### ISSUE THREAD

**Issue by senna23** [URUWorks/TeroSubtitler#315]
When a srt file which have italic lines is opened, the app trims and corrupts letters in italic at the end of the some subtitle lines. But this occurs only for Turkish subtitles. I tried for English, but didn't occur.
When opening Turkish subtitle file which is encoded in ANSI, if I select "1254:windows 1254" (or ISO 8859-9), it is opened like in the photo below. You can see the original vs corrupted one in TeroSubtitler:

![image](https://github.com/URUWorks/TeroSubtitler/assets/64222849/fe013e84-fba6-4449-be7a-50b1bfb0f7b4)

And if the file is opened and saved in TeroSubtitler, in notepad it looks like below:

before:
<i>BARRANQUILLA, KOLOMBİYA</i>
after:
<i>BARRANQUILLA, KOLOMBİ</i>}>

before:
<i><b>MEKANİK
Çeviri: batigol-7</b></i>
after:
<i><b>MEKANİK
Çeviri: batigol</b></i>}>

before:
<i>İşler</i>
after:
<i>İşl</i>}>

before:
<i>- Küresel Mühendislik.
İlan için aramıştım.</i>
after:
<i>- Küresel Mühendislik.
İlan için aramıştı</i>}>

[The Mechanic (2011).txt](https://github.com/user-attachments/files/15526637/The.Mechanic.2011.txt)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 1.0.1.19]

**Comment by URUWorks** [comment]
Can you attach said subtitle file?

**Comment by senna23** [comment]
the file is now attached at the bottom of the first message above.

**Comment by URUWorks** [comment]
Can you try this version and tell me if it works for you?

https://github.com/URUWorks/additional-files/raw/main/terosubtitler_testbuild_win64.zip
