### ISSUE TITLE
Enhance lines división for Auto-transcribed generated subtitles

### ISSUE THREAD

**Issue by cuentacuentoscaminantes** [URUWorks/TeroSubtitler#323]
The whisper voice-to-text transcripcion is really excellent. Word level detection is almost perfect. Timing is good to. But there is no reader-perspective in lines division. Human made subtitles contain some considerations in line/subtitle divisions

I would like Tero´s functionality of Voice-to-Text transcription, to consider in the creation of subtitles, some considerations regardiong the division of lines and subtitles, besides not exceeding x number of characters (which it effectebly does)

These considerations could be instructed to the transcriptor:
a) Silences and interpretative pauses (mybe + 0,5 seconds of no words) should be the place to divide lines or subtitles (regardless the length of the line/subtitle)
b) grammatical pauses and punctuation marks should be the place to divide lines or subtitles (regardless the length of the line/subtitle)
c) Write conjunctions and connections on the bottom line. (for example "and" "or", etc.)
d) Do not separate nominal, verbal and prepositional phrases into lines (for example:
![Captura de Pantalla 2024-08-27 a la(s) 19 57 15](https://github.com/user-attachments/assets/a835519b-9941-493d-98f8-e3f901b99c48)

Copio la norma UNE 153010 que es útil para comprender y implementar esto.
[UNE_153010_2012.pdf](https://github.com/user-attachments/files/16770767/UNE_153010_2012.pdf)

It would be great for the transcriptor to identify actors
Great work!! Thanks!

**Comment by chenlung** [comment]
This was already mentioned (see this: [#256]).
