### ISSUE TITLE
Make it clearer what URLs are accepted

### ISSUE THREAD

**Issue by chenlung** [URUWorks/TeroSubtitler#46]
Tero Subtitler uses yt-dlp for its Open Video from URL feature, but some users may assume it can open links from anywhere, so a list of valid websites.

Using Tero Subtitler alpha - Mac 10.11.6.

**Comment by URUWorks** [comment]
Where would you specify it?

**Comment by chenlung** [comment]
For the moment, you could put `(supports those listed here)` next to `URL` (above the text field). You can add hypertext to `here` (a link to a list of supported URLs).

**Comment by GitGianluc** [comment]
Why not as a tooltip? `Supported websites: YouTube, Vimeo` and so on

**Comment by URUWorks** [comment]
> Why not as a tooltip? `Supported websites: YouTube, Vimeo` and so on

I like it 👍

**Comment by URUWorks** [comment]
Improved v1.0.0.4
