### ISSUE TITLE
Remnants after Remove Text for Hearing Impaired

### ISSUE THREAD

**Issue by chenlung** [URUWorks/TeroSubtitler#54]
1. Open [this iTT](https://github.com/URUWorks/TeroSubtitler/files/11638293/Remnants.after.Remove.Text.for.Hearing.Impaired.zip)
2. Tools > Fix subtitles…
3. Tick 'Remove text for hearing impaired' and Apply

Desired result: hyphen is removed in the bottom line of entry 3; (empty) entries 1 and 2 are deleted
Actual result: hyphens remain in entries originally containing them; no entries are deleted

Using Tero Subtitler alpha 1 (1.0.0.0) - Mac 10.11.6.

**Comment by chenlung** [comment]
See [this](https://github.com/URUWorks/TeroSubtitler/discussions/56).

**Comment by URUWorks** [comment]
Fixed v1.0.0.2
