### ISSUE TITLE
Inaccurate warning after accessing relocated file

### ISSUE THREAD

**Issue by chenlung** [URUWorks/TeroSubtitler#55]
1. Open a file
2. Move the file from its directory
3. Open>Recent files
4. Choose the same file (of the old location)

Desired result: 'File cannot be found' (subsequently removed from list) [?]
Actual result: Dialogue: 'Error loading file, unrecognized format.'

Using Tero Subtitler alpha 1 (1.0.0.0) - Mac 10.11.6.

**Comment by URUWorks** [comment]
Fixed v1.0.0.1
