### ISSUE TITLE
Truncated text in drop-down menu

### ISSUE THREAD

**Issue by chenlung** [URUWorks/TeroSubtitler#57]
`Netflix (English) [children]`
![Fix subtitles  truncations](https://github.com/URUWorks/TeroSubtitler/assets/2973439/9d7a4be7-15bd-4be5-b731-b15921dd303b)

Using Tero Subtitler alpha 1 (1.0.0.0) - Mac 10.11.6.

**Comment by URUWorks** [comment]
I don't think it's a bug, you can move the splitter and it looks nice :)

**Comment by URUWorks** [comment]
Improved v1.0.0.8
