### ISSUE TITLE
Different default file format won't be saved in tero.cfg

### ISSUE THREAD

**Issue by GitGianluc** [URUWorks/TeroSubtitler#61]
Step to reproduce:
1. Open Tero Subtitler
2. Press “New empty subtitle”
3. Go to “Settings”
4. Set “Default file format” to “WebVTT” in “General” tab
5. Close Tero Subtitler and re-open it
6. Custom setting has been saved in “Settings” window, but “SubRip” format is still the default file format (as one can see in toolbar), because the new parameter is not updated in `tero.cfg` file (`DefEncoding="139"` won't change). 

Using Tero Subtitler alpha - macOS Ventura 13.4 / MacBook Air M2

**Comment by URUWorks** [comment]
I see, but the default format is saved, if you open settings again, "WebVTT" appears in this case; the toolbar is not updated in the main form. Correct?

**Comment by GitGianluc** [comment]
@URUWorks You're correct, but the fact that the desired default format is not saved in `tero.cfg` file and displayed in the toolbar means that – if you save the active document – the SubRip format will be set, not the .vtt format.

<img width="673" alt="SCR-20230604-bmou" src="https://github.com/URUWorks/TeroSubtitler/assets/16348719/98f0bda8-311b-4342-ba96-6f47e7621846">

Anyway, thanks for providing this brand new version of your software!  ❤️

**Comment by URUWorks** [comment]
Fixed v1.0.0.1
