### ISSUE TITLE
GUI localization: add support for multiple languages

### ISSUE THREAD

**Issue by GitGianluc** [URUWorks/TeroSubtitler#62]
Italian language would be much appreciated!  😄 

I will be very happy to contribute, if you want!

**Comment by URUWorks** [comment]
Of course, you can send me your translation ;)

**Comment by chenlung** [comment]
Do either of you (@GitGianluc, @URUWorks) have thoughts on [this](https://github.com/URUWorks/TeroSubtitler/discussions/65)?

**Comment by GitGianluc** [comment]
> Do either of you (@GitGianluc, @URUWorks) have thoughts on [this](https://github.com/URUWorks/TeroSubtitler/discussions/65)?

I used to rely on Transifex until it became a paid service (I also tried Mozilla Pontoon, but I found it quite a mess) and honestly I'm not familiar with any other translation management systems. However, I have used [Poedit software](https://poedit.net/) before…

**Comment by chenlung** [comment]
@GitGianluc Is there a way I can email you? Would like to share some files that might be useful for testing in relation to translation. :)

**Comment by GitGianluc** [comment]
Shall we finally open a free profile on Transifex to be able to translate the strings from English?

**Comment by chenlung** [comment]
Transifex account not established yet.

**Comment by GitGianluc** [comment]
😢
