### ISSUE TITLE
Some entries in iTunes Timed Text don't display at the right time in videos with non-integer rates when mpv doesn't handle subtitles

### ISSUE THREAD

**Issue by chenlung** [URUWorks/TeroSubtitler#63]
1. Open [this](https://github.com/URUWorks/TeroSubtitler/files/11640041/The.Big.Boss.English.Trailer.8.mm.iTunes.Timed.Text.zip) iTT
2. Open [this](https://github.com/URUWorks/TeroSubtitler/files/11640040/The.Big.Boss.English.Trailer.8.mm.zip) video (23.976) [discretion advised]
3. Double-click entry 4

Result: subtitle doesn't display in the video preview on the time (00:01:46:23).
![Some entries in iTunes Timed Text don't display at the right time in videos with non-integer rates  iTT](https://github.com/URUWorks/TeroSubtitler/assets/2973439/6c558b38-66a3-4d82-8d29-f759e86ae943)

Note: If you open a [WebVTT](https://github.com/URUWorks/TeroSubtitler/files/11640042/The.Big.Boss.English.Trailer.8.mm.WebVTT.zip) instead (and disable SMPTE), it will display the subtitle.
![Some entries in iTunes Timed Text don't display at the right time in videos with non-integer rates  WebVTT](https://github.com/URUWorks/TeroSubtitler/assets/2973439/25916593-3bd5-412f-9890-626e5992e0be)

Using Tero Subtitler alpha 1.0.0.0 - Mac 10.11.6.

**Comment by chenlung** [comment]
This _could_ be an mpv issue, so I'd appreciate it if someone is able to ascertain properly (and we'll hopefully have a fix).

**Comment by GitGianluc** [comment]
Same here!

<img width="1471" alt="SCR-20230603-dhdl" src="https://github.com/URUWorks/TeroSubtitler/assets/16348719/69549d2e-2878-43f7-983c-23a344454d94">
<br />
<br />
The only difference I can observe is that, after clicking on subtitle 4, the text remains selected unlike all the other subtitles, where the selection disappears after a second and the text is displayed within the video. Could this possibly have any relevance?
<br />
<br />
Using Tero Subtitler alpha - macOS Ventura 13.4 / MacBook Air M2

**Comment by chenlung** [comment]
This may also apply to other frame-based formats?

**Comment by chenlung** [comment]
I probably should say, in relation to the origins of files, that the iTT and WebVTT were produced using [Subtitle Horse](https://subtitle-horse.com) with some amendments. It seems to cope fine overall, so maybe another approach is needed for Tero Subtitler. Do we think it's an issue mpv has to address or one that can be solved ourselves?

**Comment by chenlung** [comment]
Is it possible for Tero to draw the subtitles (independently of mpv)? If I understand correctly, Subtitle Edit offers this as an option.

**Comment by chenlung** [comment]
> Is it possible for Tero to draw the subtitles (instead of mpv)? If I understand correctly, Subtitle Edit offers this as an option.

This could pose a problem for subtitle alignment (mpv may not support shifts to the top, for example).

**Comment by chenlung** [comment]
I believe this is fixed for 1.0.0.9, at least for frame-based files such as iTT? Milliseconds (those not conforming to the frame-based calculations of Tero) might be a different story, though I'm hoping that'll be addressed with a rounding function.
