### ISSUE TITLE
Shortcuts don't immediately work after start-up

### ISSUE THREAD

**Issue by chenlung** [URUWorks/TeroSubtitler#66]
1. Load Tero Subtitler
2. Click New on the start-up screen
3. Perform the shortcut for Quit (or any others)

Result: Shortcuts do nothing.

4. Click on the subtitle
5. Perform the shortcut for Quit (or anything else)

Result: Tero Subtitler quits.

Using Tero Subtitler alpha 1 (1.0.0.0) - Mac 10.11.6.

**Comment by GitGianluc** [comment]
I think it might be a window's focus issue.

**Comment by chenlung** [comment]
@URUWorks couldn't reproduce this on Windows 11.

**Comment by URUWorks** [comment]
> I think it might be a window's focus issue.

I think it's possible, maybe Tero's main window is shown without focus (in macOS)?

**Comment by GitGianluc** [comment]
> I think it's possible, maybe Tero's main window is shown without focus (in macOS)?

Taking a closer look, now I notice that – straight after opening – the focus is on the initial time of the first subtitle!

1. **Just** opened (keyboard shortcuts won't work):
<img width="1471" alt="Tero-01_Just-opened" src="https://github.com/URUWorks/TeroSubtitler/assets/16348719/1904a503-f134-4f25-8e4f-3968bc6af980">
<br /><br />

2. **After** clicking somewhere else (keyboard shortcuts will work):


<img width="1471" alt="Tero-02_After-clicking-somewhere" src="https://github.com/URUWorks/TeroSubtitler/assets/16348719/a350c7c6-f15a-4f5c-9606-9f1345a52bfe">

**Comment by URUWorks** [comment]
Fixed v1.0.0.1
