### ISSUE TITLE
Style/Actor function (and the relevant toolbar) is missing

### ISSUE THREAD

**Issue by GitGianluc** [URUWorks/TeroSubtitler#68]
Is it an intentional omission or just a simple oversight?

**Comment by URUWorks** [comment]
Should it be incorporated?

**Comment by GitGianluc** [comment]
I’d love it! The Actor function is very useful for educational purpose videos, especially while learning foreign languages, because the lines of each actor/actress can be shown or hidden at will.

**Comment by URUWorks** [comment]
Good, how would it be incorporated, same as Subtitle Workshop?

**Comment by GitGianluc** [comment]
Yes, the position of the toolbar too was handy, in my opinion. Thank you very much!

**Comment by GitGianluc** [comment]
Thanks for adding it in v[1.0.0.7](https://github.com/URUWorks/TeroSubtitler/releases/tag/1.0.0.7)!
