### ISSUE TITLE
Allow user to add cue identifiers to WebVTT upon save

### ISSUE THREAD

**Issue by chenlung** [URUWorks/TeroSubtitler#7]
Currently, WebVTT files save without numbered entries, so the user should be given the option to include or exclude them.

Using Tero Subtitler alpha - Mac 10.11.6.

**Comment by GitGianluc** [comment]
In my humble opinion, the absence of cue identifiers should be considered a regression compared to Subtitle Workshop 7.02 r3. Cue identifiers are often required in the standards of subtitles distributed in this format, and having progressive numbering is more practical than not having it... At first, I would restore the function **with** numbering.

**Comment by chenlung** [comment]
> In my humble opinion, the absence of cue identifiers should be considered a regression compared to Subtitle Workshop 7.02 r3. Cue identifiers are often required in the standards of subtitles distributed in this format, and having progressive numbering is more practical than not having it... At first, I would restore the function **with** numbering.
It's interesting that there is a requirement in some places.

I personally prefer them without (makes editing easier), but I can understand if you want to make the default with them (an option would be the best).

**Comment by GitGianluc** [comment]
> I can understand if you want to make the default with them

Thank you! Indeed, stripping extra numbers out is easier than adding them manually! 😆 

> (an option would be the best).

Yes, it definitely would!

**Comment by chenlung** [comment]
You can use [Editing Tools](https://en.editingtools.io/subtitles) in the meantime. 😄

**Comment by URUWorks** [comment]
The option will be incorporated and everyone will be able to choose. 😄

**Comment by URUWorks** [comment]
Fixed v1.0.0.1

**Comment by GitGianluc** [comment]
> Added v1.0.0.1

Thanks, I really appreciate it.

**Comment by GitGianluc** [comment]
> Added v1.0.0.1

I can't see the new feature in v1.0.0.1 / 2: when or where is the option supposed to be selectable?

**Comment by chenlung** [comment]
> > Added v1.0.0.1
> 
> I can't see the new feature in v1.0.0.1 / 2: when or where is the option supposed to be selectable?

It's in the newly introduced Format Properties.

**Comment by GitGianluc** [comment]
> It's in the newly introduced Format Properties.

I got it! I would have expected to find it as an option during the saving of a .vtt file…
