### ISSUE TITLE
[macOS] Source mode: every keyboard shortcut works but “Select all” (⌘ + A)

### ISSUE THREAD

**Issue by GitGianluc** [URUWorks/TeroSubtitler#70]
Steps to reproduce:

1. Launch Tero Subtitler.
2. Load a saved subtitle file (no matter what the file format is).
3. Switch to “Source mode”.
4. Try to cut, copy or paste something using the relevant keyboard shortcuts (⌘ + X ; ⌘ + C ; ⌘ + V respectively): you will be able to do that.
5. Try to select all the text using ⌘ + A: nothing will happen.

**Comment by URUWorks** [comment]
Fixed v1.0.0.1
