### ISSUE TITLE
Make subtitle list and video window equal size

### ISSUE THREAD

**Issue by chenlung** [URUWorks/TeroSubtitler#77]
I adjust the video preview's dimensions so that both this and the subtitle list share the same horizontal spacing.

The default has the video preview appear too small:
![Make subtitle list and video window equal size](https://github.com/URUWorks/TeroSubtitler/assets/2973439/006a2f8e-d84d-4fe5-bf6d-cb46bd415852)

- The time code is truncated.
- The subtitles won't fit (though that's [another issue](https://github.com/URUWorks/TeroSubtitler/issues/42)).

Using Tero Subtitler alpha 1 (1.0.0.0) - Mac 10.11.6.

**Comment by URUWorks** [comment]
Fixed v1.0.0.2

**Comment by chenlung** [comment]
The time codes are no longer truncated, but the video still looks like a postage stamp (and subtitles are mispresented in relation to line breaks).
![Make subtitle list and video window equal size](https://github.com/URUWorks/TeroSubtitler/assets/2973439/443e2588-d467-48be-9ee5-241dadefb649)

**Comment by GitGianluc** [comment]
It does work from my side!

<img width="1470" alt="Tero_Windows-size" src="https://github.com/URUWorks/TeroSubtitler/assets/16348719/2a1c8672-9b5b-4fde-b83a-6805f397e6b0">

**Comment by chenlung** [comment]
The default size is fine, but when expanding it becomes unequal.

**Comment by URUWorks** [comment]
I do not see it as an error, the user can modify it as he likes.

**Comment by chenlung** [comment]
If advanced users wish to adjust it, that's fine, but for new users, it would be great to have this (so that the typical CPL recommendation of 42 doesn't meet line breaks, potentially avoiding confusion).
