### ISSUE TITLE
Error when saving as MAC DVD Studio Pro

### ISSUE THREAD

**Issue by chenlung** [URUWorks/TeroSubtitler#79]
1. File > Load subtitle…
2. Choose [this](https://github.com/URUWorks/TeroSubtitler/files/11647783/Error.when.saving.as.MAC.DVD.Studio.Pro.zip) and Open
3. File > Save subtitle as…
4. Choose MAC DVD Studio Pro and Save

Result: `TRegExpr compile: *+ operand could be empty (pos 11).`
![Error when saving as MAC DVD Studio Pro](https://github.com/URUWorks/TeroSubtitler/assets/2973439/ece1424c-36cf-4b30-a374-92db48c295db)

Using Tero Subtitler alpha 1 (1.0.0.0) - Mac 10.11.6.

**Comment by chenlung** [comment]
Is this even a valid format? Perhaps it should just be removed if there's no evidence of its existence.

I was always under the impression that DVD Studio Pro only accepted .stl files (Spruce Technologies). It's a format that Tero Subtitler imports and exports, but it should be renamed to make the distinction from the EBU format.

**Comment by chenlung** [comment]
> The attached zip file is empty.

It downloads, unzips, and opens fine for me. Are you sure?

It can probably be reproduced using any file (or try the ones I've given).

**Comment by URUWorks** [comment]
Fixed v1.0.0.1
