### ISSUE TITLE
SBV > SubViewer

### ISSUE THREAD

**Issue by chenlung** [URUWorks/TeroSubtitler#80]
When opening and saving Subviewer, it is displayed as SBV (should be [SubViewer](https://support.google.com/youtube/answer/2734698?hl=en-GB#zippy=%2Cbasic-file-formats)).
![SBV   SubViewer](https://github.com/URUWorks/TeroSubtitler/assets/2973439/33e99773-abfc-4db8-959f-f0c13cf9c1a5)

Using Tero Subtitler alpha 1 (1.0.0.0) - Mac 10.11.6.

**Comment by chenlung** [comment]
Tero Subtitler saves SubViewer as .sbv, but .sub is also acceptable (according to YouTube).

**Comment by URUWorks** [comment]
Fixed v1.0.0.1
