### ISSUE TITLE
Timed-Text > Timed Text

### ISSUE THREAD

**Issue by chenlung** [URUWorks/TeroSubtitler#81]
When opening and saving, there is an option for Timed-Text, but it should be presented as [Timed Text](https://en.wikipedia.org/wiki/Timed_Text_Markup_Language).
![Timed-Text   Timed Text](https://github.com/URUWorks/TeroSubtitler/assets/2973439/7bd7ad2e-f34e-4f14-8624-6a0bd81983d2)

Using Tero Subtitler alpha 1 (1.0.0.0) - Mac 10.11.6.

**Comment by URUWorks** [comment]
Fixed v1.0.0.1
