### ISSUE TITLE
Empty warning when saving Cavena 890

### ISSUE THREAD

**Issue by chenlung** [URUWorks/TeroSubtitler#82]
1. File > Load subtitle…
2. Choose a file and Open
3. File > Save subtitle as…
4. Choose Cavena 890 and Save

Result: Empty warning; nothing saves.
![Empty warning when saving Cavena 890](https://github.com/URUWorks/TeroSubtitler/assets/2973439/bdf72df5-0813-4749-ad3e-825d8b5ae313)

Using Tero Subtitler alpha 1 (1.0.0.0) - Mac 10.11.6.

**Comment by URUWorks** [comment]
Fixed v1.0.0.1
