### ISSUE TITLE
Empty warning when saving DVDSubtitle

### ISSUE THREAD

**Issue by chenlung** [URUWorks/TeroSubtitler#83]
1. File > Load subtitle…
2. Choose a file and Open
3. File > Save subtitle as…
4. Choose DVDSubtitle and Save

Result: Empty warning; nothing saves.
![Empty warning when saving DVDSubtitle](https://github.com/URUWorks/TeroSubtitler/assets/2973439/5cdb31ae-4b13-4a7f-91fe-8c8503828435)

Using Tero Subtitler alpha 1 (1.0.0.0) - Mac 10.11.6.

**Comment by URUWorks** [comment]
Fixed v1.0.0.1
