### ISSUE TITLE
Empty warning when saving EBU Subtitling Format

### ISSUE THREAD

**Issue by chenlung** [URUWorks/TeroSubtitler#84]
1. File > Load subtitle…
2. Choose a file and Open
3. File > Save subtitle as…
4. Choose EBU Subtitling Format and Save

Result: Empty warning; nothing saves.
![Empty warning when saving EBU Subtitling Format](https://github.com/URUWorks/TeroSubtitler/assets/2973439/5c21a1db-36ca-4dfe-a149-c7ec67c1b6dc)

Using Tero Subtitler alpha 1 (1.0.0.0) - Mac 10.11.6.

**Comment by URUWorks** [comment]
Fixed v1.0.0.1
