### ISSUE TITLE
Empty warning when saving second Karaoke Lyrics LRC

### ISSUE THREAD

**Issue by chenlung** [URUWorks/TeroSubtitler#85]
1. File > Load subtitle…
2. Choose a file and Open
3. File > Save subtitle as…
4. Choose second Karaoke Lyrics LRC and Save

Result: Empty warning; nothing saves.
![Empty warning when saving second Karaoke Lyrics LRC](https://github.com/URUWorks/TeroSubtitler/assets/2973439/f3ee9243-d28d-498e-90a7-125aa96bb605)

Using Tero Subtitler alpha 1 (1.0.0.0) - Mac 10.11.6.

**Comment by URUWorks** [comment]
Fixed v1.0.0.1
