### ISSUE TITLE
Empty warning when saving second MPlayer

### ISSUE THREAD

**Issue by chenlung** [URUWorks/TeroSubtitler#86]
1. File > Load subtitle…
2. Choose a file and Open
3. File > Save subtitle as…
4. Choose second MPlayer and Save

Result: Empty warning; nothing saves.
![Empty warning when saving second MPlayer](https://github.com/URUWorks/TeroSubtitler/assets/2973439/96081095-e03d-4b97-a586-44491c7a31c0)

Using Tero Subtitler alpha 1 (1.0.0.0) - Mac 10.11.6.

**Comment by URUWorks** [comment]
Fixed v1.0.0.1
