### ISSUE TITLE
Error when loading Advanced Subtitles.xas

### ISSUE THREAD

**Issue by chenlung** [URUWorks/TeroSubtitler#89]
1. File > Load subtitle…
2. Choose [this](https://github.com/URUWorks/TeroSubtitler/files/11648114/Error.when.loading.Advanced.Subtitles.xas.iTT.zip) iTT and Open
3. File > Save subtitle as…
4. Choose Advanced Subtitles.xas and Save
5. File > Load subtitle…
6. Choose the xas (available [here](https://github.com/URUWorks/TeroSubtitler/files/11648116/Error.when.loading.Advanced.Subtitles.xas.zip)) and Open

Result: `Error loading file, unrecognized format.`
![Error when loading Advanced Subtitles xas](https://github.com/URUWorks/TeroSubtitler/assets/2973439/85cec846-3a7f-42d9-99af-f9548378c3a7)

Using Tero Subtitler alpha 1 (1.0.0.0) - Mac 10.11.6.

**Comment by chenlung** [comment]
Where is the official specification? Upon a quick search, there is [this](https://en.wikipedia.org/wiki/Advanced_Content).

**Comment by URUWorks** [comment]
Fixed v1.0.0.1

**Comment by chenlung** [comment]
Doesn't seem fixed.

Using Tero Subtitler alpha 1.0.0.2 - Mac 10.11.6.
