### ISSUE TITLE
Error when loading GPAC TTXT.ttxt

### ISSUE THREAD

**Issue by chenlung** [URUWorks/TeroSubtitler#90]
1. File > Load subtitle…
2. Choose [this](https://github.com/URUWorks/TeroSubtitler/files/11648127/Error.when.loading.GPAC.TTXT.ttxt.iTT.zip) iTT and Open
3. File > Save subtitle as…
4. Choose GPAC TTXT.ttxt and Save
5. File > Load subtitle…
6. Choose the ttxt (available [here](https://github.com/URUWorks/TeroSubtitler/files/11648131/Error.when.loading.GPAC.TTXT.ttxt.ttxt.zip)) and Open

Result: `Error loading file, unrecognized format.`
![Error when loading GPAC TTXT ttxt](https://github.com/URUWorks/TeroSubtitler/assets/2973439/e0e06b08-98b9-4736-b424-788a5ca1db81)

Using Tero Subtitler alpha 1 (1.0.0.0) - Mac 10.11.6.

**Comment by chenlung** [comment]
Is [this](https://github.com/gpac/gpac/wiki/Subtitling-with-GPAC) the format's specification?

**Comment by URUWorks** [comment]
Fixed v1.0.0.1
