### ISSUE TITLE
Remnants of previously loaded video present when loading a subtitle file with no video previously attributed

### ISSUE THREAD

**Issue by chenlung** [URUWorks/TeroSubtitler#91]
1. File > Load subtitle…
2. Choose a file and open
3. Video > Open…
4. Play until something is seen and pause
5. Choose a file and Open
6. File > Load subtitle…
7. Choose a file that has never had a video opened with it and Open

Result: Video preview shows the frame and time code from the video loaded, but it's residual (can't be played, etc. A video has to be loaded/re-loaded for it to work).

Using Tero Subtitler alpha 1 (1.0.0.0) - Mac 10.11.6.

**Comment by URUWorks** [comment]
Fixed v1.0.0.1
