### ISSUE TITLE
[macOS – ARM64] Tero 1.0.0.1: EXC_BAD_ACCESS (SIGKILL (Code Signature Invalid))

### ISSUE THREAD

**Issue by GitGianluc** [URUWorks/TeroSubtitler#98]
After upgrading to the [new release](https://github.com/URUWorks/TeroSubtitler/releases/tag/1.0.0.1), Tero 1.0.0.1 crashes on startup and can't be opened on Apple M2 MacBook Air running macOS Ventura 13.4 ([full log output](https://github.com/URUWorks/TeroSubtitler/files/11714381/Tero_crash-log.txt)).

Tero Subtitler 1.0.0.0 keeps on running smoothly instead.

**Comment by URUWorks** [comment]
this version includes the binaries for arm64 and x86_64.. something is wrong in the arm64 version,
I will upload an update only with x86_64 (like 1.0.0.0) until I discover the flaw. 🤕

**Comment by GitGianluc** [comment]
> I will upload an update only with x86_64 (like 1.0.0.0) until I discover the flaw. 🤕

Thanks! The [x86_64 version](https://github.com/URUWorks/TeroSubtitler/releases/download/1.0.0.0/ts1000_macos64.zip) of Tero 1.0.0.0 used to work (and still works) like a charm on ARM64! 😄

**Comment by URUWorks** [comment]
Fixed v1.0.0.2

**Comment by chenlung** [comment]
Can there be a note or a reminder somewhere that the ARM build is an issue?

**Comment by GitGianluc** [comment]
> Can there be a note or a reminder somewhere that the ARM build is an issue?

https://github.com/URUWorks/TeroSubtitler/discussions/97#discussioncomment-6144532

**Comment by chenlung** [comment]
> > Can there be a note or a reminder somewhere that the ARM build is an issue?
> 
> [#97 (comment)](https://github.com/URUWorks/TeroSubtitler/discussions/97#discussioncomment-6144532)

Yes, but something that mentions that building for ARM is a problem (the only solution at the moment is a stop-gap: making just the Intel build available). We should file something or re-open this so others can help as well.

**Comment by GitGianluc** [comment]
Tero Subtitler 1.0.0.2 is running in my MacBook Air M2!  🥳

**Comment by chenlung** [comment]
> Tero Subtitler 1.0.0.2 is running in my MacBook Air M2! 🥳

Rosetta 2?

**Comment by GitGianluc** [comment]
No checkbox “Open using Rosetta” available in the application info pane, so that it doesn't look like Rosetta is intervening. But of course it is, indeed…

<img width="617" alt="TeroSubtitler-Intel" src="https://github.com/URUWorks/TeroSubtitler/assets/16348719/53e0ce53-7f1a-4158-aab6-82b24a90bbb0">
