### ISSUE TITLE
[enhancement] Inaccurate message within the update dialogue box

### ISSUE THREAD

**Issue by GitGianluc** [URUWorks/TeroSubtitler#99]
<img width="512" alt="Screenshot 2023-06-11 alle 12 12 23" src="https://github.com/URUWorks/TeroSubtitler/assets/16348719/c3be4549-092b-4057-a840-4dd7da45a262">

@chenlung Wouldn't it be more accurate to say “[changelog](https://en.wikipedia.org/wiki/Changelog)” rather than “[change list](https://en.wikipedia.org/wiki/Version_control#Common_terminology)”?

**Comment by URUWorks** [comment]
Ok

**Comment by GitGianluc** [comment]
Let's wait for a confirmation by the only native speaker in the village!  🤣

**Comment by URUWorks** [comment]
and the number one 🥇

**Comment by chenlung** [comment]
Yes, changelog better!

Your English is sometimes better than mine, @GitGianluc!

**Comment by URUWorks** [comment]
Fixed v1.0.0.2

**Comment by GitGianluc** [comment]
That’s so kind from you! ☺️
